# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WorkQuestions.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QShortcut , QMessageBox, QDialog, QLineEdit, QFormLayout, QVBoxLayout, QDialogButtonBox , QFileDialog , QAction ,QShortcut
from WorkQuestionsContinued import Ui_WorkQCont

thisdict = {"Never":0,
            "Very Rarely":1,
            "Rarely":2,
            "Sometimes":3,
            "Often":4,
            "Always":5}

class Ui_Dialog(object):

    def __init__(self,email,birth,edu,lead,workyears):

        self.email = email
        self.birth = birth
        self.edu = edu             #lines 16 to 20 are getting the detials from the login screen to call on the DB here
        self.lead = lead
        self.workyears = workyears
        

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(812, 719)
        Dialog.setStyleSheet("\n"
"background-color: rgb(230, 253, 255);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 10, 741, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 601, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 611, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 601, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 290, 601, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 370, 601, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 430, 601, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(10, 490, 601, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(10, 550, 601, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(10, 610, 611, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.NextWorkQ = QtWidgets.QPushButton(Dialog)
        self.NextWorkQ.setGeometry(QtCore.QRect(690, 680, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NextWorkQ.setFont(font)
        self.NextWorkQ.setAutoFillBackground(False)
        self.NextWorkQ.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.NextWorkQ.setObjectName("NextWorkQ")
        self.Back = QtWidgets.QPushButton(Dialog)
        self.Back.setGeometry(QtCore.QRect(10, 680, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Back.setFont(font)
        self.Back.setAutoFillBackground(False)
        self.Back.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Back.setObjectName("Back")
        self.WorkQ1 = QtWidgets.QComboBox(Dialog)
        self.WorkQ1.setGeometry(QtCore.QRect(650, 80, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.WorkQ1.setFont(font)
        self.WorkQ1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WorkQ1.setMaxVisibleItems(6)
        self.WorkQ1.setObjectName("WorkQ1")
        self.WorkQ1.addItem("")
        self.WorkQ1.addItem("")
        self.WorkQ1.addItem("")
        self.WorkQ1.addItem("")
        self.WorkQ1.addItem("")
        self.WorkQ1.addItem("")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(-10, 110, 831, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(0, 170, 831, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(0, 260, 831, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(0, 350, 831, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(0, 400, 831, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Dialog)
        self.line_6.setGeometry(QtCore.QRect(0, 460, 831, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(Dialog)
        self.line_7.setGeometry(QtCore.QRect(0, 520, 831, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(Dialog)
        self.line_8.setGeometry(QtCore.QRect(-10, 580, 831, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(Dialog)
        self.line_9.setGeometry(QtCore.QRect(-10, 650, 831, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.WorkQ2 = QtWidgets.QComboBox(Dialog)
        self.WorkQ2.setGeometry(QtCore.QRect(650, 140, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.WorkQ2.setFont(font)
        self.WorkQ2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WorkQ2.setMaxVisibleItems(6)
        self.WorkQ2.setObjectName("WorkQ2")
        self.WorkQ2.addItem("")
        self.WorkQ2.addItem("")
        self.WorkQ2.addItem("")
        self.WorkQ2.addItem("")
        self.WorkQ2.addItem("")
        self.WorkQ2.addItem("")
        self.WorkQ3 = QtWidgets.QComboBox(Dialog)
        self.WorkQ3.setGeometry(QtCore.QRect(650, 210, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.WorkQ3.setFont(font)
        self.WorkQ3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WorkQ3.setMaxVisibleItems(6)
        self.WorkQ3.setObjectName("WorkQ3")
        self.WorkQ3.addItem("")
        self.WorkQ3.addItem("")
        self.WorkQ3.addItem("")
        self.WorkQ3.addItem("")
        self.WorkQ3.addItem("")
        self.WorkQ3.addItem("")
        self.WorkQ4 = QtWidgets.QComboBox(Dialog)
        self.WorkQ4.setGeometry(QtCore.QRect(650, 300, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.WorkQ4.setFont(font)
        self.WorkQ4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WorkQ4.setMaxVisibleItems(6)
        self.WorkQ4.setObjectName("WorkQ4")
        self.WorkQ4.addItem("")
        self.WorkQ4.addItem("")
        self.WorkQ4.addItem("")
        self.WorkQ4.addItem("")
        self.WorkQ4.addItem("")
        self.WorkQ4.addItem("")
        self.WorkQ5 = QtWidgets.QComboBox(Dialog)
        self.WorkQ5.setGeometry(QtCore.QRect(650, 370, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.WorkQ5.setFont(font)
        self.WorkQ5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WorkQ5.setMaxVisibleItems(6)
        self.WorkQ5.setObjectName("WorkQ5")
        self.WorkQ5.addItem("")
        self.WorkQ5.addItem("")
        self.WorkQ5.addItem("")
        self.WorkQ5.addItem("")
        self.WorkQ5.addItem("")
        self.WorkQ5.addItem("")
        self.WorkQ6 = QtWidgets.QComboBox(Dialog)
        self.WorkQ6.setGeometry(QtCore.QRect(650, 430, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.WorkQ6.setFont(font)
        self.WorkQ6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WorkQ6.setMaxVisibleItems(6)
        self.WorkQ6.setObjectName("WorkQ6")
        self.WorkQ6.addItem("")
        self.WorkQ6.addItem("")
        self.WorkQ6.addItem("")
        self.WorkQ6.addItem("")
        self.WorkQ6.addItem("")
        self.WorkQ6.addItem("")
        self.WorkQ7 = QtWidgets.QComboBox(Dialog)
        self.WorkQ7.setGeometry(QtCore.QRect(650, 490, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.WorkQ7.setFont(font)
        self.WorkQ7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WorkQ7.setMaxVisibleItems(6)
        self.WorkQ7.setObjectName("WorkQ7")
        self.WorkQ7.addItem("")
        self.WorkQ7.addItem("")
        self.WorkQ7.addItem("")
        self.WorkQ7.addItem("")
        self.WorkQ7.addItem("")
        self.WorkQ7.addItem("")
        self.WorkQ8 = QtWidgets.QComboBox(Dialog)
        self.WorkQ8.setGeometry(QtCore.QRect(650, 550, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.WorkQ8.setFont(font)
        self.WorkQ8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WorkQ8.setMaxVisibleItems(6)
        self.WorkQ8.setObjectName("WorkQ8")
        self.WorkQ8.addItem("")
        self.WorkQ8.addItem("")
        self.WorkQ8.addItem("")
        self.WorkQ8.addItem("")
        self.WorkQ8.addItem("")
        self.WorkQ8.addItem("")
        self.WorkQ9 = QtWidgets.QComboBox(Dialog)
        self.WorkQ9.setGeometry(QtCore.QRect(650, 610, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.WorkQ9.setFont(font)
        self.WorkQ9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WorkQ9.setMaxVisibleItems(6)
        self.WorkQ9.setObjectName("WorkQ9")
        self.WorkQ9.addItem("")
        self.WorkQ9.addItem("")
        self.WorkQ9.addItem("")
        self.WorkQ9.addItem("")
        self.WorkQ9.addItem("")
        self.WorkQ9.addItem("")


        self.retranslateUi(Dialog)
        self.WorkQ1.setCurrentIndex(-1)
        self.WorkQ2.setCurrentIndex(-1)
        self.WorkQ3.setCurrentIndex(-1)
        self.WorkQ4.setCurrentIndex(-1)
        self.WorkQ5.setCurrentIndex(-1)
        self.WorkQ6.setCurrentIndex(-1)
        self.WorkQ7.setCurrentIndex(-1)
        self.WorkQ8.setCurrentIndex(-1)
        self.WorkQ9.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.NextWorkQ.clicked.connect(self.pressed)
        self.h = Dialog
        

    def pressed(self):
        if(self.WorkQ1.currentText() == "" or self.WorkQ2.currentText() == "" or self.WorkQ3.currentText() == "" or self.WorkQ4.currentText() == "" or self.WorkQ5.currentText() == "" or self.WorkQ6.currentText() == "" or self.WorkQ7.currentText() == "" or self.WorkQ8.currentText() == "" or self.WorkQ9.currentText() == ""):

            self.messagebox("Error","Please enter all fields")

        else: 

            self.WorkQ1 = self.WorkQ1.currentText() 
            self.WorkQ2 = self.WorkQ2.currentText() 
            self.WorkQ3 = self.WorkQ3.currentText() 
            self.WorkQ4 = self.WorkQ4.currentText() 
            self.WorkQ5 = self.WorkQ5.currentText() 
            self.WorkQ6 = self.WorkQ6.currentText() 
            self.WorkQ7 = self.WorkQ7.currentText() 
            self.WorkQ8 = self.WorkQ8.currentText() 
            self.WorkQ9 = self.WorkQ9.currentText() 

            

            self.WorkQtoWorkContinued(self.email,self.birth,self.edu,self.lead,self.workyears,self.WorkQ1,self.WorkQ2,self.WorkQ3,self.WorkQ4,self.WorkQ5,self.WorkQ6,self.WorkQ7,self.WorkQ8,self.WorkQ9)
            self.h.hide()

    def WorkQtoWorkContinued(self,email,birth,edu,lead,workyears,WorkQ1,WorkQ2,WorkQ3,WorkQ4,WorkQ5,WorkQ6,WorkQ7,WorkQ8,WorkQ9): 

        self.main = QtWidgets.QMainWindow() 

        self.ui = Ui_WorkQCont(self.email,self.birth,self.edu,self.lead,self.workyears,self.WorkQ1,self.WorkQ2,self.WorkQ3,self.WorkQ4,self.WorkQ5,self.WorkQ6,self.WorkQ7,self.WorkQ8,self.WorkQ9) 
        self.ui.setupUi(self.main)
        self.main.show()   

    def messagebox(self,title,message):
        mess = QtWidgets.QMessageBox()

        mess.setWindowTitle(title)                          
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()   



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "COTG"))
        self.label.setText(_translate("Dialog", "Please answer the following questions regarding working in an organisation "))
        self.label_2.setText(_translate("Dialog", "In the wider organisation, some people struggle to fit in because they are different"))
        self.label_3.setText(_translate("Dialog", "When someone in the organisation makes a mistake, it is often held against him/her"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p>Sometimes people in this organisation deliberately act in a way that undermines </p><p>others\' efforts</p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p>In the organisation generally, people are free to take risks that don\'t endanger</p><p>others or the future of the organisation</p></body></html>"))
        self.label_6.setText(_translate("Dialog", "We value each other\'s unique skills and talents"))
        self.label_7.setText(_translate("Dialog", "The culture encourages anyone to be able to bring up problems and tough issues"))
        self.label_8.setText(_translate("Dialog", "It is difficult to ask colleagues for help in my organisation"))
        self.label_9.setText(_translate("Dialog", "When expectations are met, people know"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p>The organisation is very attentive to dealing with mistakes, complaints and failures</p></body></html>"))
        self.NextWorkQ.setStatusTip(_translate("Dialog", "Click this to go to next questions"))
        self.NextWorkQ.setText(_translate("Dialog", "Next"))
        self.Back.setStatusTip(_translate("Dialog", "Click this to go back a form"))
        self.Back.setText(_translate("Dialog", "Back"))
        self.WorkQ1.setToolTip(_translate("Dialog", "Please select from the following"))
        self.WorkQ1.setItemText(0, _translate("Dialog", "Never"))
        self.WorkQ1.setItemText(1, _translate("Dialog", "Very Rarely"))
        self.WorkQ1.setItemText(2, _translate("Dialog", "Rarely"))
        self.WorkQ1.setItemText(3, _translate("Dialog", "Sometimes"))
        self.WorkQ1.setItemText(4, _translate("Dialog", "Often"))
        self.WorkQ1.setItemText(5, _translate("Dialog", "Always"))
        self.WorkQ2.setToolTip(_translate("Dialog", "Please select from the following"))
        self.WorkQ2.setItemText(0, _translate("Dialog", "Never"))
        self.WorkQ2.setItemText(1, _translate("Dialog", "Very Rarely"))
        self.WorkQ2.setItemText(2, _translate("Dialog", "Rarely"))
        self.WorkQ2.setItemText(3, _translate("Dialog", "Sometimes"))
        self.WorkQ2.setItemText(4, _translate("Dialog", "Often"))
        self.WorkQ2.setItemText(5, _translate("Dialog", "Always"))
        self.WorkQ3.setToolTip(_translate("Dialog", "Please select from the following"))
        self.WorkQ3.setItemText(0, _translate("Dialog", "Never"))
        self.WorkQ3.setItemText(1, _translate("Dialog", "Very Rarely"))
        self.WorkQ3.setItemText(2, _translate("Dialog", "Rarely"))
        self.WorkQ3.setItemText(3, _translate("Dialog", "Sometimes"))
        self.WorkQ3.setItemText(4, _translate("Dialog", "Often"))
        self.WorkQ3.setItemText(5, _translate("Dialog", "Always"))
        self.WorkQ4.setToolTip(_translate("Dialog", "Please select from the following"))
        self.WorkQ4.setItemText(0, _translate("Dialog", "Never"))
        self.WorkQ4.setItemText(1, _translate("Dialog", "Very Rarely"))
        self.WorkQ4.setItemText(2, _translate("Dialog", "Rarely"))
        self.WorkQ4.setItemText(3, _translate("Dialog", "Sometimes"))
        self.WorkQ4.setItemText(4, _translate("Dialog", "Often"))
        self.WorkQ4.setItemText(5, _translate("Dialog", "Always"))
        self.WorkQ5.setToolTip(_translate("Dialog", "Please select from the following"))
        self.WorkQ5.setItemText(0, _translate("Dialog", "Never"))
        self.WorkQ5.setItemText(1, _translate("Dialog", "Very Rarely"))
        self.WorkQ5.setItemText(2, _translate("Dialog", "Rarely"))
        self.WorkQ5.setItemText(3, _translate("Dialog", "Sometimes"))
        self.WorkQ5.setItemText(4, _translate("Dialog", "Often"))
        self.WorkQ5.setItemText(5, _translate("Dialog", "Always"))
        self.WorkQ6.setToolTip(_translate("Dialog", "Please select from the following"))
        self.WorkQ6.setItemText(0, _translate("Dialog", "Never"))
        self.WorkQ6.setItemText(1, _translate("Dialog", "Very Rarely"))
        self.WorkQ6.setItemText(2, _translate("Dialog", "Rarely"))
        self.WorkQ6.setItemText(3, _translate("Dialog", "Sometimes"))
        self.WorkQ6.setItemText(4, _translate("Dialog", "Often"))
        self.WorkQ6.setItemText(5, _translate("Dialog", "Always"))
        self.WorkQ7.setToolTip(_translate("Dialog", "Please select from the following"))
        self.WorkQ7.setItemText(0, _translate("Dialog", "Never"))
        self.WorkQ7.setItemText(1, _translate("Dialog", "Very Rarely"))
        self.WorkQ7.setItemText(2, _translate("Dialog", "Rarely"))
        self.WorkQ7.setItemText(3, _translate("Dialog", "Sometimes"))
        self.WorkQ7.setItemText(4, _translate("Dialog", "Often"))
        self.WorkQ7.setItemText(5, _translate("Dialog", "Always"))
        self.WorkQ8.setToolTip(_translate("Dialog", "Please select from the following"))
        self.WorkQ8.setItemText(0, _translate("Dialog", "Never"))
        self.WorkQ8.setItemText(1, _translate("Dialog", "Very Rarely"))
        self.WorkQ8.setItemText(2, _translate("Dialog", "Rarely"))
        self.WorkQ8.setItemText(3, _translate("Dialog", "Sometimes"))
        self.WorkQ8.setItemText(4, _translate("Dialog", "Often"))
        self.WorkQ8.setItemText(5, _translate("Dialog", "Always"))
        self.WorkQ9.setToolTip(_translate("Dialog", "Please select from the following"))
        self.WorkQ9.setItemText(0, _translate("Dialog", "Never"))
        self.WorkQ9.setItemText(1, _translate("Dialog", "Very Rarely"))
        self.WorkQ9.setItemText(2, _translate("Dialog", "Rarely"))
        self.WorkQ9.setItemText(3, _translate("Dialog", "Sometimes"))
        self.WorkQ9.setItemText(4, _translate("Dialog", "Often"))
        self.WorkQ9.setItemText(5, _translate("Dialog", "Always"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    app.exec_()
